import{useState,useEffect}from"react";
const SK="stairclimb-logs-v1",SEL="stairclimb-selected-v1",GC=800,GE=30,GS=12,GST=10000,GW=128,ED=new Date("2026-09-12");
const ID=[{id:1,date:"2026-06-17",workouts:[{type:"Military HIIT",duration:39,calories:316},{type:"Stair Climb (Down)",duration:4,calories:26},{type:"Stair Climb (Up)",duration:3,calories:35}],totalActiveCal:1181,exerciseMin:58,standHrs:16,steps:8941,distanceMi:4.06,stairFlights:22,stairLoad:"Backpack ~15lbs + Uniform + Boots",waterOz:0,notes:"Day 1. Strong start. Water intake — area to improve."}];
const load=()=>{try{const r=localStorage.getItem(SK);return r?JSON.parse(r):ID;}catch{return ID;}};
const save=(l)=>{try{localStorage.setItem(SK,JSON.stringify(l));}catch(e){}};
const loadSel=(l)=>{try{const r=localStorage.getItem(SEL);return r?JSON.parse(r):l[0]?.id||1;}catch{return l[0]?.id||1;}};
const days=()=>Math.ceil((ED-new Date())/(86400000));
const inp={background:"#0a0a18",border:"1px solid #1c1c2e",borderRadius:8,color:"#fff",padding:"9px 12px",fontSize:16,width:"100%",boxSizing:"border-box",WebkitAppearance:"none"};
const lbl={color:"#555",fontSize:10,marginBottom:4,display:"block",textTransform:"uppercase",letterSpacing:"0.08em"};
const card={background:"#0d0d1a",borderRadius:16,padding:16,marginBottom:14,border:"1px solid #1c1c2e"};
function SBar({label,value,goal,color,unit}){const p=Math.min((value/goal)*100,100),o=value>=goal;return(<div style={{marginBottom:10}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:3}}><span style={{color:"#777",fontSize:12}}>{label}</span><span style={{color:o?color:"#ccc",fontSize:12,fontWeight:600}}>{typeof value==="number"&&value%1!==0?value.toFixed(2):value.toLocaleString()}<span style={{color:"#444",fontSize:10}}> / {goal} {unit}</span>{o&&<span style={{color,marginLeft:4}}>✓</span>}</span></div><div style={{background:"#111",borderRadius:4,height:5}}><div style={{width:`${p}%`,background:color,height:"100%",borderRadius:4}}/></div></div>);}
function Ring({value,goal,color,label,unit,size=78}){const p=Math.min(value/goal,1.5),r=(size-14)/2,c=2*Math.PI*r,f=Math.min(p,1)*c,o=p>1?(p-1)*c:0;return(<div style={{display:"flex",flexDirection:"column",alignItems:"center",gap:4}}><svg width={size}height={size}style={{transform:"rotate(-90deg)"}}><circle cx={size/2}cy={size/2}r={r}fill="none"stroke="#1a1a2e"strokeWidth={11}/><circle cx={size/2}cy={size/2}r={r}fill="none"stroke={color}strokeWidth={11}strokeDasharray={`${f} ${c-f}`}strokeLinecap="round"opacity={0.95}/>{o>0&&<circle cx={size/2}cy={size/2}r={r}fill="none"stroke="#fff"strokeWidth={7}strokeDasharray={`${o} ${c-o}`}strokeLinecap="round"opacity={0.5}/>}</svg><div style={{textAlign:"center"
